Retrieves a list of all countries from an API.

Returns:
    list: A list of country codes.

In [8]:
import time
import requests
from database_connector_countries import *

def get_all_countries_from_api():
    country_map = []
    url = "https://wft-geo-db.p.rapidapi.com/v1/geo/countries"
    headers = {
        "X-RapidAPI-Key": "bcb6679012msh169f4edcd407c6dp17800bjsnb43444ccba7a",
        "X-RapidAPI-Host": "wft-geo-db.p.rapidapi.com"
    }
    countries = []
    page = 1
    while True:
        params = {
            "offset": len(countries),
            "limit": 10  # Adjust the limit as per your requirement
        }
        response = requests.get(url, headers=headers, params=params, timeout=5)
        data = response.json()
        countries.extend(data['data'])
        if len(countries) >= data['metadata']['totalCount']:
            break
        page += 1
        time.sleep(2)
        country_map.extend([country['code'] for country in data['data']])

    return country_map

Creates a database with the given name and creates a table with the given query

In [9]:
from database_connector_countries import *

try:
    create_database("countries.db", '''CREATE TABLE IF NOT EXISTS Countries (
                            country_id INTEGER PRIMARY KEY AUTOINCREMENT,
                            code TEXT
                        )''')
    print("Database and table created successfully.")
except Exception as e:
    print(f"An error occurred: {str(e)}")

Database and table created successfully.

   Inserts countries into the 'countries.db' database using data obtained from an API.
   
   This function calls the 'insert_countries' function to insert the countries into the database.
   If successful, it prints a success message. If an error occurs, it prints the error message.

In [10]:
from database_connector_countries import *

try:
   insert_countries("countries.db", get_all_countries_from_api())
   print("Countries added successfully.")
except Exception as e:
   print(f"An error occurred: {str(e)}")

Countries added successfully.

Displays the list of countries stored in the specified database.

In [11]:
from database_connector_countries import *
try:
    show_countries("countries.db")
except Exception as e:
    print(f"An error occurred: {str(e)}")

(1, 'AF')
(2, 'AL')
(3, 'DZ')
(4, 'AD')
(5, 'AO')
(6, 'AG')
(7, 'AR')
(8, 'AM')
(9, 'AU')
(10, 'AT')
(11, 'AZ')
(12, 'BH')
(13, 'BD')
(14, 'BB')
(15, 'BY')
(16, 'BE')
(17, 'BZ')
(18, 'BJ')
(19, 'BT')
(20, 'BO')
(21, 'BA')
(22, 'BW')
(23, 'BR')
(24, 'BN')
(25, 'BG')
(26, 'BF')
(27, 'BI')
(28, 'KH')
(29, 'CM')
(30, 'CA')
(31, 'CV')
(32, 'CF')
(33, 'TD')
(34, 'CL')
(35, 'CO')
(36, 'KM')
(37, 'CK')
(38, 'CR')
(39, 'HR')
(40, 'CU')
(41, 'CY')
(42, 'CZ')
(43, 'CD')
(44, 'DK')
(45, 'DJ')
(46, 'DM')
(47, 'DO')
(48, 'EC')
(49, 'EG')
(50, 'SV')
(51, 'GQ')
(52, 'ER')
(53, 'EE')
(54, 'SZ')
(55, 'ET')
(56, 'FM')
(57, 'FJ')
(58, 'FI')
(59, 'FR')
(60, 'GA')
(61, 'GE')
(62, 'DE')
(63, 'GH')
(64, 'GR')
(65, 'GD')
(66, 'GT')
(67, 'GN')
(68, 'GW')
(69, 'GY')
(70, 'HT')
(71, 'HN')
(72, 'HK')
(73, 'HU')
(74, 'IS')
(75, 'IN')
(76, 'ID')
(77, 'IR')
(78, 'IQ')
(79, 'IE')
(80, 'IL')
(81, 'IT')
(82, 'CI')
(83, 'JM')
(84, 'JP')
(85, 'JO')
(86, 'KZ')
(87, 'KE')
(88, 'KI')
(89, 'XK')
(90, 'KW')
(91, 'KG')
(92, 'LA')
(93, 'LV')
(94, 'LB')
(95, 'LS')
(96, 'LR')
(97, 'LY')
(98, 'LI')
(99, 'LT')
(100, 'LU')
(101, 'MG')
(102, 'MW')
(103, 'MY')
(104, 'MV')
(105, 'ML')
(106, 'MT')
(107, 'MH')
(108, 'MR')
(109, 'MU')
(110, 'MX')
(111, 'MD')
(112, 'MC')
(113, 'MN')
(114, 'ME')
(115, 'MA')
(116, 'MZ')
(117, 'MM')
(118, 'NA')
(119, 'NR')
(120, 'NP')
(121, 'NL')
(122, 'NZ')
(123, 'NI')
(124, 'NE')
(125, 'NG')
(126, 'NU')
(127, 'KP')
(128, 'MK')
(129, 'NO')
(130, 'OM')
(131, 'PK')
(132, 'PW')
(133, 'PA')
(134, 'PG')
(135, 'PY')
(136, 'CN')
(137, 'PE')
(138, 'PH')
(139, 'PL')
(140, 'PT')
(141, 'QA')
(142, 'CG')
(143, 'RO')
(144, 'RU')
(145, 'RW')
(146, 'KN')
(147, 'LC')
(148, 'VC')
(149, 'WS')
(150, 'SM')
(151, 'SA')
(152, 'SN')
(153, 'RS')
(154, 'SC')
(155, 'SL')
(156, 'SG')
(157, 'SK')
(158, 'SI')
(159, 'SB')
(160, 'SO')
(161, 'ZA')
(162, 'KR')
(163, 'SS')
(164, 'ES')
(165, 'LK')
(166, 'SD')
(167, 'SR')
(168, 'SE')
(169, 'CH')
(170, 'SY')
(171, 'ST')
(172, 'TW')
(173, 'TJ')
(174, 'TZ')
(175, 'TH')
(176, 'BS')
(177, 'GM')
(178, 'TL')
(179, 'TG')
(180, 'TO')
(181, 'TT')
(182, 'TN')
(183, 'TR')
(184, 'TM')
(185, 'TV')
(186, 'UG')
(187, 'UA')
(188, 'AE')
(189, 'GB')
(190, 'US')

Drops a table from the specified database.
(Uncomment to drop the 'Countries' table when updating the database with new data. Refer to the README for more details.)

In [12]:
#from database_connector_countries import *

#try:
#    drop_table("countries.db", "Countries")
#except Exception as e:
#    print(f"An error occurred: {str(e)}")